name: Build and Deploy OCI Image

on:
  push:
    tags:
      - 'v*'

jobs:
  registry_publish_workflow:
    uses: turbot/steampipe-workflows/.github/workflows/registry-publish.yml@main
    secrets: inherit
    runs-on:
      labels: ubuntu_4_core
